In [1]:
print("Hello World!")

Hello World!


In [21]:
arr=[1,2,0,2,4,0,1,3,0,54,2,0,2,0,0,0,2,4,5,6]
# arr=[0,0,0,2,1,3]
for i in range(len(arr)-1):
    if(arr[i]==0):
        for j in range(i+1,len(arr)):
            if(arr[j]!=0):
                t=arr[j]
                arr[j]=arr[i]
                arr[i]=t
                break

print(arr)

[1, 2, 2, 4, 1, 3, 54, 2, 2, 2, 4, 5, 6, 0, 0, 0, 0, 0, 0, 0]


In [25]:
arr=[0,0,0,31,6,5]
c=0
l=[]
for i in range(len(arr)):
    if(arr[i]==0):
        c+=1
        continue
    l.append(arr[i])
for i in range(c):
    l.append(0)
print(l)
arr.clear()
arr.extend(l)

[31, 6, 5, 0, 0, 0]


In [3]:
from numpy import *

In [4]:
a=array([[2,-4,0],[-4,8,0],[0,0,8]])
print(a)

[[ 2 -4  0]
 [-4  8  0]
 [ 0  0  8]]


In [5]:
eig,eigvec=linalg.eig(a)

In [6]:
print(eig)

[ 0. 10.  8.]


In [5]:
print(eigvec)

[[-0.83025082  0.55738997]
 [-0.55738997 -0.83025082]]


In [2]:
import sympy as sy

In [3]:
a=sy.Matrix([[5,4,2],[0,5,0],[0,0,5]])

In [5]:
S,J=a.jordan_form()

In [6]:
J

Matrix([
[5, 1, 0],
[0, 5, 0],
[0, 0, 5]])

In [7]:
S

Matrix([
[4, 0,    0],
[0, 1, -1/2],
[0, 0,    1]])

In [3]:

from numpy import *
A=array([[1,0,1],[-1,1,0]])

In [4]:
A.T

array([[ 1, -1],
       [ 0,  1],
       [ 1,  0]])

In [9]:
x=A@A.T
print(x)

[[ 2 -1]
 [-1  2]]


In [7]:
linalg.eig(x)

EigResult(eigenvalues=array([3., 1.]), eigenvectors=array([[ 0.70710678,  0.70710678],
       [-0.70710678,  0.70710678]]))

In [8]:
linalg.eig(A.T@A)

EigResult(eigenvalues=array([ 3.00000000e+00, -2.91433544e-16,  1.00000000e+00]), eigenvectors=array([[-8.16496581e-01,  5.77350269e-01, -1.57009246e-16],
       [ 4.08248290e-01,  5.77350269e-01,  7.07106781e-01],
       [-4.08248290e-01, -5.77350269e-01,  7.07106781e-01]]))

In [10]:
c=array([[14,-11],[-11,23]])

In [11]:
linalg.eig(c)

EigResult(eigenvalues=array([ 6.61513568, 30.38486432]), eigenvectors=array([[-0.83025082,  0.55738997],
       [-0.55738997, -0.83025082]]))

In [14]:
from numpy import *

In [15]:
s=array([[3.3,-0.3],[-0.3,5.5]])
b=array([[29.16,20.52],[20.52,14.44]])

In [16]:
linalg.eig(linalg.inv(s)@b)

EigResult(eigenvalues=array([12.20066445,  0.        ]), eigenvectors=array([[ 0.90878558, -0.57549341],
       [ 0.41726342,  0.81780642]]))

In [ ]:
import cv2
def noise():
cap = cv2.VideoCapture(0)
while True:
_, frame1 = cap.read()
_, frame2 = cap.read()
diff = cv2.absdiff(frame2, frame1)
diff = cv2.cvtColor(diff, cv2.COLOR_BGR2GRAY)
diff = cv2.blur(diff, (5,5))
_, thresh = cv2.threshold(diff, 25, 255, cv2.THRESH_BINARY)
contr, _ = cv2.findContours(thresh, cv2.RETR_TREE,
cv2.CHAIN_APPROX_SIMPLE)
if len(contr) > 0:
max_cnt = max(contr, key=cv2.contourArea)
x,y,w,h = cv2.boundingRect(max_cnt)
cv2.rectangle(frame1, (x, y), (x+w, y+h), (0,255,0),
2) cv2.putText(frame1, "MOTION", (10,80),
cv2.FONT_HERSHEY_SIMPLEX, 2, (0,255,0), 2)
else:
cv2.putText(frame1, "NO-MOTION", (10,80),
cv2.FONT_HERSHEY_SIMPLEX, 2, (0,0,255), 2)
cv2.imshow("esc. to exit", frame1)
if cv2.waitKey(1) == 27:
cap.release()
cv2.destroyAllWindows()
break
#Record:
import cv2
from datetime import datetime
def record():

cap = cv2.VideoCapture(0)fourcc = cv2.VideoWriter_fourcc(*'XVID')
out = cv2.VideoWriter(f'recordings/{datetime.now().strftime("%H-
%M- %S")}.avi', fourcc,20.0,(640,480))
while True:


_, frame = cap.read()
cv2.putText(frame, f'{datetime.now().strftime("%D-%H-%M-%S")}',
(50,50), cv2.FONT_HERSHEY_COMPLEX,
0.6, (255,255,255), 2)
out.write(frame)
cv2.imshow("esc. to stop", frame)
if cv2.waitKey(1) == 27:
cap.release()
cv2.destroyAllWindows()
break

In [ ]:
import tkinter as tk
import tkinter.font as font
from in_out import in_out
from motion import noise
from rect_noise import rect_noise
from record import record
from PIL import Image, ImageTk
from find_motion import find_motion
from identify import maincall
window = tk.Tk()
window.title("Smart cctv")
window.iconphoto(False,
tk.PhotoImage(file='mn.png'))
window.geometry('1080x700')
frame1 = tk.Frame(window)
label_title = tk.Label(frame1, text="Smart cctv Camera")
label_font = font.Font(size=35,
weight='bold',family='Helvetica') label_title['font'] =
label_font
label_title.grid(pady=(10,10), column=2)
icon = Image.open('icons/spy.png')
icon = icon.resize((150,150), Image.ANTIALIAS)
icon = ImageTk.PhotoImage(icon)
label_icon = tk.Label(frame1, image=icon)
label_icon.grid(row=1, pady=(5,10), column=2)
btn1_image = Image.open('icons/lamp.png')
btn1_image = btn1_image.resize((50,50),
Image.ANTIALIAS) btn1_image =
ImageTk.PhotoImage(btn1_image)
btn2_image = Image.open('icons/rectangle-of-cutted-line-geometrical
shape.png')
btn2_image = btn2_image.resize((50,50),
Image.ANTIALIAS) btn2_image =
ImageTk.PhotoImage(btn2_image)
btn5_image = Image.open('icons/exit.png')
btn5_image = btn5_image.resize((50,50),
Image.ANTIALIAS) btn5_image =
ImageTk.PhotoImage(btn5_image)
btn3_image = Image.open('icons/security-camera.png')
btn3_image = btn3_image.resize((50,50),
Image.ANTIALIAS) btn3_image =ImageTk.PhotoImage(btn3_image)

btn6_image = Image.open('icons/incognito.png')
btn6_image = btn6_image.resize((50,50), Image.ANTIALIAS)
btn6_image = ImageTk.PhotoImage(btn6_image)
btn4_image = Image.open('icons/recording.png')
btn4_image = btn4_image.resize((50,50), Image.ANTIALIAS)
btn4_image = ImageTk.PhotoImage(btn4_image)
btn7_image = Image.open('icons/recording.png')
btn7_image = btn7_image.resize((50,50), Image.ANTIALIAS)
btn7_image = ImageTk.PhotoImage(btn7_image)

#Button
btn_font = font.Font(size=25)
btn1 = tk.Button(frame1, text='Monitor', height=90, width=180,
fg='green',command = find_motion, image=btn1_image, compound='left')
btn1['font'] = btn_font
btn1.grid(row=3, pady=(20,10))
btn2 = tk.Button(frame1, text='Rectangle', height=90, width=180,
fg='orange', command=rect_noise, compound='left', image=btn2_image)
btn2['font'] = btn_font
btn2.grid(row=3, pady=(20,10), column=3, padx=(20,5))
btn_font = font.Font(size=25)
btn3 = tk.Button(frame1, text='Noise', height=90, width=180, fg='green',
command=noise, image=btn3_image, compound='left')
btn3['font'] = btn_font
btn3.grid(row=5, pady=(20,10))
btn4 = tk.Button(frame1, text='Record', height=90, width=180, fg='orange',
command=record, image=btn4_image, compound='left')
btn4['font'] = btn_font
btn4.grid(row=5, pady=(20,10), column=3)
btn6 = tk.Button(frame1, text='In Out', height=90, width=180, fg='green',
command=in_out, image=btn6_image, compound='left')
btn6['font'] = btn_font
btn6.grid(row=5, pady=(20,10), column=2)
btn5 = tk.Button(frame1, height=90, width=180, fg='red',
command=window.quit, image=btn5_image)
btn5['font'] = btn_font
btn5.grid(row=6, pady=(20,10), column=2)
btn7 = tk.Button(frame1, text="identify", fg="orange",command=maincall,
compound='left', image=btn7_image, height=90, width=180)45
btn7['font'] = btn_font
btn7.grid(row=3, column=2, pady=(20,10))
frame1.pack()
window.mainloop()


In [ ]:
import cv2
def noise():
cap = cv2.VideoCapture(0)
while True:
_, frame1 = cap.read()
_, frame2 = cap.read()
diff = cv2.absdiff(frame2, frame1)
diff = cv2.cvtColor(diff, cv2.COLOR_BGR2GRAY)
diff = cv2.blur(diff, (5,5))
_, thresh = cv2.threshold(diff, 25, 255, cv2.THRESH_BINARY)
contr, _ = cv2.findContours(thresh, cv2.RETR_TREE,
cv2.CHAIN_APPROX_SIMPLE)
if len(contr) > 0:
max_cnt = max(contr, key=cv2.contourArea)
x,y,w,h = cv2.boundingRect(max_cnt)
cv2.rectangle(frame1, (x, y), (x+w, y+h), (0,255,0),
2) cv2.putText(frame1, "MOTION", (10,80),
cv2.FONT_HERSHEY_SIMPLEX, 2, (0,255,0), 2)
else:
cv2.putText(frame1, "NO-MOTION", (10,80),
cv2.FONT_HERSHEY_SIMPLEX, 2, (0,0,255), 2)
cv2.imshow("esc. to exit", frame1)
if cv2.waitKey(1) == 27:
cap.release()
cv2.destroyAllWindows()
break

IndentationError: expected an indented block after function definition on line 2 (2419429958.py, line 3)